require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'

target 'SwiftTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Pods for SwiftTest

  target 'SwiftTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  target 'SwiftTestUITests' do
    # Pods for testing
  end

end
